# see http://docs.travis-ci.com/user/languages/csharp/

language: csharp

solution: src/mono/WampSharpMono.sln

install:
  - travis_retry nuget restore src/mono/Newtonsoft.Msgpack.Mono.sln

script:
  - xbuild /p:Configuration=Release src/mono/Newtonsoft.Msgpack.Mono.sln
